### ISSUE TITLE
Broken charge mode

### ISSUE THREAD

**Issue by instanttim** [jepefe/monitormate#2]
Somehow I broke the "show charge mode" feature. I haven't looked at it for too long, but it wasn't apparent to me how it was supposed to work.

NOTE: this issue is only in the "instanttim" branch right now.

**Comment by jepefe** [comment]
Wrong div id as parameter to set_chart() function when calling from charge mode checkbox.

Now should work.

**Comment by instanttim** [comment]
This didn't work in my install.

**Comment by jepefe** [comment]
Works for me. 
http://jeperez.com/old/monitormate/monitormate.html

I don't know why changing date doesn't work but in today data you can see the three first points changin it's color.

**Comment by instanttim** [comment]
I sure hope that's sample data! 100 days since full charge!

Hmm, it's not working with my copy. I wonder why.

**Comment by instanttim** [comment]
Oh, never mind. You don't show Silent or Bulk modes... thus i was looking at today and i haven't hit absorb yet! Sorry.
