### ISSUE TITLE
FNDC's SOC has a leading zero in it when it is less than 100.

### ISSUE THREAD

**Issue by instanttim** [jepefe/monitormate#6]
This is on-disk in the matelog file, I believe it's coming over in the JSON feed that way as well. The python script collecting the data from the Mate needs to be checked, perhaps the mate is even sending that percentage as three digits even though other SOC data showing in the summary doesn't have leading zeros.

**Comment by jepefe** [comment]
Cast string to int soc value on flexnetdc.py.
