### ISSUE TITLE
Staggering of column charts breaks clickable charts (a bit)

### ISSUE THREAD

**Issue by instanttim** [jepefe/monitormate#7]
To stagger the columns in the historical charts I shifted the time
stamps forward and backward. I tried some Flot plugins that did the same thing without modifying the timestamps and they didn't work well. So as it is, the production column is in the _previous_ day so if you click on tuesday's production column the daily charts will change to show monday. The tooltips reflect this incorrect information.

So when using Flot, I suppose I should give up on the side-by-side columns. I've already corrected this in my fork using Highcharts since it supports staggered columns.

Jesús, what do you think?

![screen_shot_2014-01-20_at_10_15_39_am-6](https://f.cloud.github.com/assets/6156678/1956874/24256586-81ff-11e3-9825-781841351775.png)

**Comment by jepefe** [comment]
heheh, we were working in the same thing at same time! I opened a Issue and marked as closed.  Please check my changes and if works for you we could consider it as a fixed issue.

**Comment by instanttim** [comment]
yeah, seems fine given the constraints of Flot.

https://github.com/jepefe/monitormate/commit/6679092278eb7ebd07c9791597b31e6747f2544e
