### ISSUE TITLE
Charge Params Met

### ISSUE THREAD

**Issue by instanttim** [jepefe/monitormate#9]
I'm just noticing that my system has never logged a "yes" for charge params set. I see the days since full resetting to 0.0 when i reach full charge and my FNDC/MATE3 shows that the parameters are met. Is it possible there something wrong in the python side of things?

**Comment by instanttim** [comment]
I looked at the python, it looks fine. I guess I need to test this at a moment when the charge params HAVE been met and really inspect the data coming from the Mate's UDP stream.

**Comment by jepefe** [comment]
The python code has not been changed from the first release. I notice that
is working right in some installations. Maybe a firmware update has caused
malfunction.

2014-02-24 19:00 GMT+00:00 Timothy Martin notifications@github.com:

**Comment by instanttim** [comment]
Yeah. The python looks fine. I am very suspect of my fndc these days
